/**
 *
 * $Id$
 */
package ucof.devices.devicetypes.validation;

import ucof.devices.devicetypes.a653components.ModuleSchedule;

import ucof.devices.devicetypes.a653components.a653partition.ModulePartitions;

import ucof.devices.devicetypes.a653components.healthmanagement.HealthManagement;

/**
 * A sample validator interface for {@link ucof.devices.devicetypes.SuperA653ModuleType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperA653ModuleTypeValidator {
	boolean validate();

	boolean validateHealthManagement(HealthManagement value);
	boolean validateModuleSchedule(ModuleSchedule value);
	boolean validatePartitions(ModulePartitions value);
}
