/**
 */
package targets.configdesk.dSpaceArinc825.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import targets.configdesk.dSpaceArinc825.util.DSpaceArinc825AdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DSpaceArinc825ItemProviderAdapterFactory extends DSpaceArinc825AdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DSpaceArinc825ItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.configdesk.dSpaceArinc825.A825Configuration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A825ConfigurationItemProvider a825ConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link targets.configdesk.dSpaceArinc825.A825Configuration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA825ConfigurationAdapter() {
		if (a825ConfigurationItemProvider == null) {
			a825ConfigurationItemProvider = new A825ConfigurationItemProvider(this);
		}

		return a825ConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.configdesk.dSpaceArinc825.SignalModelAccessStatus} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SignalModelAccessStatusItemProvider signalModelAccessStatusItemProvider;

	/**
	 * This creates an adapter for a {@link targets.configdesk.dSpaceArinc825.SignalModelAccessStatus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSignalModelAccessStatusAdapter() {
		if (signalModelAccessStatusItemProvider == null) {
			signalModelAccessStatusItemProvider = new SignalModelAccessStatusItemProvider(this);
		}

		return signalModelAccessStatusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.configdesk.dSpaceArinc825.FeatureTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureTriggerItemProvider featureTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link targets.configdesk.dSpaceArinc825.FeatureTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureTriggerAdapter() {
		if (featureTriggerItemProvider == null) {
			featureTriggerItemProvider = new FeatureTriggerItemProvider(this);
		}

		return featureTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.configdesk.dSpaceArinc825.FeatureCyclicTimingControl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureCyclicTimingControlItemProvider featureCyclicTimingControlItemProvider;

	/**
	 * This creates an adapter for a {@link targets.configdesk.dSpaceArinc825.FeatureCyclicTimingControl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureCyclicTimingControlAdapter() {
		if (featureCyclicTimingControlItemProvider == null) {
			featureCyclicTimingControlItemProvider = new FeatureCyclicTimingControlItemProvider(this);
		}

		return featureCyclicTimingControlItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.configdesk.dSpaceArinc825.FeatureRawData} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureRawDataItemProvider featureRawDataItemProvider;

	/**
	 * This creates an adapter for a {@link targets.configdesk.dSpaceArinc825.FeatureRawData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureRawDataAdapter() {
		if (featureRawDataItemProvider == null) {
			featureRawDataItemProvider = new FeatureRawDataItemProvider(this);
		}

		return featureRawDataItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.configdesk.dSpaceArinc825.FeatureEnable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureEnableItemProvider featureEnableItemProvider;

	/**
	 * This creates an adapter for a {@link targets.configdesk.dSpaceArinc825.FeatureEnable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureEnableAdapter() {
		if (featureEnableItemProvider == null) {
			featureEnableItemProvider = new FeatureEnableItemProvider(this);
		}

		return featureEnableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.configdesk.dSpaceArinc825.FeatureFrameAccess} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureFrameAccessItemProvider featureFrameAccessItemProvider;

	/**
	 * This creates an adapter for a {@link targets.configdesk.dSpaceArinc825.FeatureFrameAccess}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureFrameAccessAdapter() {
		if (featureFrameAccessItemProvider == null) {
			featureFrameAccessItemProvider = new FeatureFrameAccessItemProvider(this);
		}

		return featureFrameAccessItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (a825ConfigurationItemProvider != null) a825ConfigurationItemProvider.dispose();
		if (signalModelAccessStatusItemProvider != null) signalModelAccessStatusItemProvider.dispose();
		if (featureTriggerItemProvider != null) featureTriggerItemProvider.dispose();
		if (featureCyclicTimingControlItemProvider != null) featureCyclicTimingControlItemProvider.dispose();
		if (featureRawDataItemProvider != null) featureRawDataItemProvider.dispose();
		if (featureEnableItemProvider != null) featureEnableItemProvider.dispose();
		if (featureFrameAccessItemProvider != null) featureFrameAccessItemProvider.dispose();
	}

}
