/**
 */
package ucof.communication.configECIC.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import ucof.communication.configECIC.util.ConfigECICAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ConfigECICItemProviderAdapterFactory extends ConfigECICAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ConfigECICItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.ED247Configurations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ED247ConfigurationsItemProvider ed247ConfigurationsItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.ED247Configurations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createED247ConfigurationsAdapter() {
		if (ed247ConfigurationsItemProvider == null) {
			ed247ConfigurationsItemProvider = new ED247ConfigurationsItemProvider(this);
		}

		return ed247ConfigurationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.ED247Configuration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ED247ConfigurationItemProvider ed247ConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.ED247Configuration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createED247ConfigurationAdapter() {
		if (ed247ConfigurationItemProvider == null) {
			ed247ConfigurationItemProvider = new ED247ConfigurationItemProvider(this);
		}

		return ed247ConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.FileProducer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileProducerItemProvider fileProducerItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.FileProducer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFileProducerAdapter() {
		if (fileProducerItemProvider == null) {
			fileProducerItemProvider = new FileProducerItemProvider(this);
		}

		return fileProducerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.Channels} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChannelsItemProvider channelsItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.Channels}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChannelsAdapter() {
		if (channelsItemProvider == null) {
			channelsItemProvider = new ChannelsItemProvider(this);
		}

		return channelsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.Channel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChannelItemProvider channelItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.Channel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChannelAdapter() {
		if (channelItemProvider == null) {
			channelItemProvider = new ChannelItemProvider(this);
		}

		return channelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.ComInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComInterfaceItemProvider comInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.ComInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComInterfaceAdapter() {
		if (comInterfaceItemProvider == null) {
			comInterfaceItemProvider = new ComInterfaceItemProvider(this);
		}

		return comInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.UDPSockets} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UDPSocketsItemProvider udpSocketsItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.UDPSockets}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUDPSocketsAdapter() {
		if (udpSocketsItemProvider == null) {
			udpSocketsItemProvider = new UDPSocketsItemProvider(this);
		}

		return udpSocketsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.UDPSocket} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UDPSocketItemProvider udpSocketItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.UDPSocket}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUDPSocketAdapter() {
		if (udpSocketItemProvider == null) {
			udpSocketItemProvider = new UDPSocketItemProvider(this);
		}

		return udpSocketItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.srcDirectionExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected srcDirectionExtensionItemProvider srcDirectionExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.srcDirectionExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createsrcDirectionExtensionAdapter() {
		if (srcDirectionExtensionItemProvider == null) {
			srcDirectionExtensionItemProvider = new srcDirectionExtensionItemProvider(this);
		}

		return srcDirectionExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.Header} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HeaderItemProvider headerItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.Header}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHeaderAdapter() {
		if (headerItemProvider == null) {
			headerItemProvider = new HeaderItemProvider(this);
		}

		return headerItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (ed247ConfigurationsItemProvider != null) ed247ConfigurationsItemProvider.dispose();
		if (ed247ConfigurationItemProvider != null) ed247ConfigurationItemProvider.dispose();
		if (fileProducerItemProvider != null) fileProducerItemProvider.dispose();
		if (channelsItemProvider != null) channelsItemProvider.dispose();
		if (channelItemProvider != null) channelItemProvider.dispose();
		if (comInterfaceItemProvider != null) comInterfaceItemProvider.dispose();
		if (udpSocketsItemProvider != null) udpSocketsItemProvider.dispose();
		if (udpSocketItemProvider != null) udpSocketItemProvider.dispose();
		if (srcDirectionExtensionItemProvider != null) srcDirectionExtensionItemProvider.dispose();
		if (headerItemProvider != null) headerItemProvider.dispose();
	}

}
