/**
 *
 * $Id$
 */
package targets.intrepidgateway.validation;


/**
 * A sample validator interface for {@link targets.intrepidgateway.CanMailboxOutSlot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CanMailboxOutSlotValidator {
	boolean validate();

	boolean validatePortId(String value);
	boolean validateSourceAddressSymbol(String value);
	boolean validateSourceAddressValue(int value);
	boolean validateDestinationAddressSymbol(String value);
	boolean validateDestinationAddressValue(int value);
	boolean validateMulticast(boolean value);
}
