/**
 *
 * $Id$
 */
package targets.intrepidgateway.validation;

import org.eclipse.emf.common.util.EList;
import targets.intrepidgateway.CanMailboxAddressFilter;
import targets.intrepidgateway.CanMailboxOutSlot;


/**
 * A sample validator interface for {@link targets.intrepidgateway.MsgBoxExtension}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MsgBoxExtensionValidator {
	boolean validate();

	boolean validateNumOfOutgoingMailboxes(int value);
	boolean validateNumOfIncomingMailboxes(int value);
	boolean validateSmallBufferSize(int value);
	boolean validateSmallBufferCount(int value);
	boolean validateMediumBufferSize(int value);
	boolean validateMediumBufferCount(int value);
	boolean validateBigBufferSize(int value);
	boolean validateBigBufferCount(int value);
	boolean validateNodeAddr(int value);

	boolean validateNodeAddressSymbol(String value);

	boolean validateIncomingDestinationFilter(EList<CanMailboxAddressFilter> value);

	boolean validateSenderSourceFilter(EList<CanMailboxAddressFilter> value);

	boolean validateOutgoingMailboxSlot(EList<CanMailboxOutSlot> value);
}
