/**
 *
 * $Id$
 */
package targets.MotorController.validation;

import targets.MotorController.esconPorts;

/**
 * A sample validator interface for {@link targets.MotorController.escon409510}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface escon409510Validator {
	boolean validate();

	boolean validatePorts(esconPorts value);

	boolean validateEsconPorts(esconPorts value);
}
