/**
 *
 * $Id$
 */
package targets.MotorController.validation;

import org.eclipse.emf.common.util.EList;

import targets.MotorController.esconPort;

/**
 * A sample validator interface for {@link targets.MotorController.esconPorts}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface esconPortsValidator {
	boolean validate();

	boolean validatePort(EList<esconPort> value);

	boolean validateEsconPort(EList<esconPort> value);
}
