/**
 *
 * $Id$
 */
package ucof.communication.arinc825.validation;


/**
 * A sample validator interface for {@link ucof.communication.arinc825.A825Bus}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface A825BusValidator {
	boolean validate();

	boolean validateBaudRate(int value);
}
