/**
 *
 * $Id$
 */
package targets.rdc.validation;

import targets.intrepidgateway.MsgBoxExtension;

import targets.rdc.stmPorts;
import targets.rdc.stmTimingConfig;

/**
 * A sample validator interface for {@link targets.rdc.stm32f446re}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface stm32f446reValidator {
	boolean validate();

	boolean validateSize(String value);

	boolean validatePorts(stmPorts value);
	boolean validateStmTimingConfig(stmTimingConfig value);
	boolean validateMsgBoxExtension(MsgBoxExtension value);
}
