/**
 *
 * $Id$
 */
package targets.RDC.validation;

import targets.RDC.stmPorts;

/**
 * A sample validator interface for {@link targets.RDC.stm32f446re}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface stm32f446reValidator {
	boolean validate();

	boolean validatePorts(stmPorts value);

	boolean validateStmPorts(stmPorts value);
}
