/**
 *
 * $Id$
 */
package targets.RDC.validation;

import org.eclipse.emf.common.util.EList;

import targets.RDC.stmPort;

/**
 * A sample validator interface for {@link targets.RDC.stmPorts}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface stmPortsValidator {
	boolean validate();

	boolean validatePort(EList<stmPort> value);

	boolean validateStmPort(EList<stmPort> value);
}
