/**
 *
 * $Id$
 */
package targets.rdc.validation;


/**
 * A sample validator interface for {@link targets.rdc.stmTimingConfig}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface stmTimingConfigValidator {
	boolean validate();

	boolean validateRateDriverFrequencyHz(int value);
	boolean validateRateGroupDivisor1(int value);
	boolean validateRateGroupDivisor2(int value);
	boolean validateRateGroupDivisor3(int value);
	boolean validateRateGroupDefaultOffset(int value);
	boolean validatePwmResolutionBits(int value);

	boolean validateRateDriverFrequencyHzSize(String value);

	boolean validateRateGroupDivisor1Size(String value);

	boolean validateRateGroupDivisor2Size(String value);

	boolean validateRateGroupDivisor3Size(String value);

	boolean validateRateGroupDefaultOffsetSize(String value);

	boolean validatePwmResolutionBitsSize(String value);
}
