/**
 *
 * $Id$
 */
package targets.Sheild.validation;

import targets.Sheild.sheildPorts;

/**
 * A sample validator interface for {@link targets.Sheild.arduinosheild}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface arduinosheildValidator {
	boolean validate();

	boolean validatePorts(sheildPorts value);

	boolean validateSheildPorts(sheildPorts value);
}
