/**
 *
 * $Id$
 */
package targets.Sheild.validation;

import org.eclipse.emf.common.util.EList;

import targets.Sheild.sheildPort;

/**
 * A sample validator interface for {@link targets.Sheild.sheildPorts}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface sheildPortsValidator {
	boolean validate();

	boolean validatePort(EList<sheildPort> value);

	boolean validateSheildPort(EList<sheildPort> value);
}
