/**
 *
 * $Id$
 */
package ucof.communication.configECIC.validation;

import org.eclipse.emf.common.util.EList;

import ucof.communication.configECIC.ComInterface;
import ucof.communication.configECIC.Header;
import ucof.communication.configECIC.StandardRevisionType;

import ucof.communication.configECIC.streamTypes.SuperStreamType;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.Channel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChannelValidator {
	boolean validate();

	boolean validateFrameFormat(StandardRevisionType value);
	boolean validateComInterface(ComInterface value);
	boolean validateHeader(Header value);
	boolean validateStream(EList<SuperStreamType> value);
}
