/**
 *
 * $Id$
 */
package ucof.communication.configECIC.validation;

import org.eclipse.emf.common.util.EList;

import ucof.communication.configECIC.ED247Configuration;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.ED247Configurations}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ED247ConfigurationsValidator {
	boolean validate();

	boolean validateEd247Configuration(EList<ED247Configuration> value);
}
