/**
 *
 * $Id$
 */
package ucof.communication.configECIC.validation;

import ucof.communication.configECIC.Channels;
import ucof.communication.configECIC.ComponentTypeType;
import ucof.communication.configECIC.FileProducer;
import ucof.communication.configECIC.StandardRevisionType;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.ED247Configuration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ED247ConfigurationValidator {
	boolean validate();

	boolean validateStandardRevision(StandardRevisionType value);
	boolean validateComponentVersion(String value);
	boolean validateComponentType(ComponentTypeType value);
	boolean validateChannels(Channels value);
	boolean validateFileProducer(FileProducer value);
}
