/**
 *
 * $Id$
 */
package ucof.communication.configECIC.validation;

import org.eclipse.emf.common.util.EList;

import ucof.common.enums.PortDirectionType;

import ucof.communication.configECIC.srcDirectionExtension;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.UDPSocket}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UDPSocketValidator {
	boolean validate();

	boolean validateMulticastInterfaceIP(String value);
	boolean validateMulticastTTL(int value);
	boolean validateSrcDirectionExtension(EList<srcDirectionExtension> value);
	boolean validateDirection(PortDirectionType value);
	boolean validateIpAdress(String value);
	boolean validatePort(Integer value);
}
