/**
 */
package ucof.assignments.database.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import ucof.assignments.database.util.DatabaseAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DatabaseItemProviderAdapterFactory extends DatabaseAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DatabaseItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.database.SignalToTargetAssignmentSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SignalToTargetAssignmentSetItemProvider signalToTargetAssignmentSetItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.database.SignalToTargetAssignmentSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSignalToTargetAssignmentSetAdapter() {
		if (signalToTargetAssignmentSetItemProvider == null) {
			signalToTargetAssignmentSetItemProvider = new SignalToTargetAssignmentSetItemProvider(this);
		}

		return signalToTargetAssignmentSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.database.SignalToTargetAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SignalToTargetAssignmentItemProvider signalToTargetAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.database.SignalToTargetAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSignalToTargetAssignmentAdapter() {
		if (signalToTargetAssignmentItemProvider == null) {
			signalToTargetAssignmentItemProvider = new SignalToTargetAssignmentItemProvider(this);
		}

		return signalToTargetAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.database.PayloadToTargetAssignmentSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PayloadToTargetAssignmentSetItemProvider payloadToTargetAssignmentSetItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.database.PayloadToTargetAssignmentSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPayloadToTargetAssignmentSetAdapter() {
		if (payloadToTargetAssignmentSetItemProvider == null) {
			payloadToTargetAssignmentSetItemProvider = new PayloadToTargetAssignmentSetItemProvider(this);
		}

		return payloadToTargetAssignmentSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.database.PayloadToTargetAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PayloadToTargetAssignmentItemProvider payloadToTargetAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.database.PayloadToTargetAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPayloadToTargetAssignmentAdapter() {
		if (payloadToTargetAssignmentItemProvider == null) {
			payloadToTargetAssignmentItemProvider = new PayloadToTargetAssignmentItemProvider(this);
		}

		return payloadToTargetAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.database.MessageToTargetAssignmentSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MessageToTargetAssignmentSetItemProvider messageToTargetAssignmentSetItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.database.MessageToTargetAssignmentSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMessageToTargetAssignmentSetAdapter() {
		if (messageToTargetAssignmentSetItemProvider == null) {
			messageToTargetAssignmentSetItemProvider = new MessageToTargetAssignmentSetItemProvider(this);
		}

		return messageToTargetAssignmentSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.database.MessageToTargetAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MessageToTargetAssignmentItemProvider messageToTargetAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.database.MessageToTargetAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMessageToTargetAssignmentAdapter() {
		if (messageToTargetAssignmentItemProvider == null) {
			messageToTargetAssignmentItemProvider = new MessageToTargetAssignmentItemProvider(this);
		}

		return messageToTargetAssignmentItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (signalToTargetAssignmentSetItemProvider != null) signalToTargetAssignmentSetItemProvider.dispose();
		if (signalToTargetAssignmentItemProvider != null) signalToTargetAssignmentItemProvider.dispose();
		if (payloadToTargetAssignmentSetItemProvider != null) payloadToTargetAssignmentSetItemProvider.dispose();
		if (payloadToTargetAssignmentItemProvider != null) payloadToTargetAssignmentItemProvider.dispose();
		if (messageToTargetAssignmentSetItemProvider != null) messageToTargetAssignmentSetItemProvider.dispose();
		if (messageToTargetAssignmentItemProvider != null) messageToTargetAssignmentItemProvider.dispose();
	}

}
