/**
 *
 * $Id$
 */
package ucof.communication.validation;

import org.eclipse.emf.common.util.EList;

import ucof.communication.Database;

import ucof.communication.comDevices.CommunicationDevices;

import ucof.communication.configECIC.ED247Configurations;

import ucof.communication.connectors.Connectors;

/**
 * A sample validator interface for {@link ucof.communication.Communication}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CommunicationValidator {
	boolean validate();

	boolean validateDatabase(Database value);
	boolean validateConnectors(Connectors value);
	boolean validateEd247Configurations(ED247Configurations value);
	boolean validateCommunicationDevices(EList<CommunicationDevices> value);
}
