/**
 *
 * $Id$
 */
package ucof.communication.validation;

import ucof.communication.DataTypes;
import ucof.communication.Endianess;
import ucof.communication.SignedUnsigned;

import ucof.communication.arinc429.A429SignalSpecification;

/**
 * A sample validator interface for {@link ucof.communication.Signal}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SignalValidator {
	boolean validate();

	boolean validateDataType(DataTypes value);
	boolean validateSignedness(SignedUnsigned value);
	boolean validateBitLength(int value);
	boolean validateFactor(double value);
	boolean validateOffset(double value);
	boolean validateMinValue(double value);
	boolean validateMaxValue(double value);
	boolean validateUnit(String value);
	boolean validateByteOrder(Endianess value);
	boolean validateA429Specification(A429SignalSpecification value);
}
