/**
 *
 * $Id$
 */
package ucof.devices.functions.routing.validation;

import ucof.communication.Payload;

/**
 * A sample validator interface for {@link ucof.devices.functions.routing.PayloadRouting}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PayloadRoutingValidator {
	boolean validate();

	boolean validateInPayload(Payload value);
	boolean validateOutPayload(Payload value);
}
