/**
 *
 * $Id$
 */
package ucof.devices.functions.routing.validation;

import org.eclipse.emf.common.util.EList;

import ucof.devices.functions.routing.PayloadRouting;
import ucof.devices.functions.routing.SignalRouting;

/**
 * A sample validator interface for {@link ucof.devices.functions.routing.Routing}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoutingValidator {
	boolean validate();

	boolean validatePayloadRouting(EList<PayloadRouting> value);
	boolean validateSignalRouting(EList<SignalRouting> value);
}
