/**
 *
 * $Id$
 */
package ucof.devices.functions.routing.validation;

import ucof.communication.Signal;

/**
 * A sample validator interface for {@link ucof.devices.functions.routing.SignalRouting}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SignalRoutingValidator {
	boolean validate();

	boolean validateInSignal(Signal value);
	boolean validateOutSignal(Signal value);
}
