/**
 *
 * $Id$
 */
package ucof.communication.arinc429.validation;

import ucof.common.enums.SDITypes;

import ucof.communication.arinc429.SSMTypes;

/**
 * A sample validator interface for {@link ucof.communication.arinc429.A429Message}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface A429MessageValidator {
	boolean validate();

	boolean validateSdi(SDITypes value);
	boolean validateA429Label(SSMTypes value);
	boolean validateA429SSM(String value);
	boolean validateLabelNumber(int value);
}
