/**
 *
 * $Id$
 */
package ucof.communication.arinc429.validation;

import ucof.communication.arinc429.CodingTypes;

/**
 * A sample validator interface for {@link ucof.communication.arinc429.A429SignalSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface A429SignalSpecificationValidator {
	boolean validate();

	boolean validateCodingType(CodingTypes value);
	boolean validateFieldLength(int value);
}
