/**
 *
 * $Id$
 */
package targets.HallSensor.validation;

import targets.HallSensor.hallPorts;

/**
 * A sample validator interface for {@link targets.HallSensor.mts360}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface mts360Validator {
	boolean validate();

	boolean validatePorts(hallPorts value);

	boolean validateHallPorts(hallPorts value);
}
