/**
 *
 * $Id$
 */
package ucof.communication.comDevices.validation;

import org.eclipse.emf.common.util.EList;

import ucof.communication.comDevices.SuperCommunicationDeviceType;

/**
 * A sample validator interface for {@link ucof.communication.comDevices.CommunicationDevices}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CommunicationDevicesValidator {
	boolean validate();

	boolean validateCommunicationDevice(EList<SuperCommunicationDeviceType> value);
}
