/**
 */
package ucof.assignments.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import ucof.assignments.util.AssignmentsAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AssignmentsItemProviderAdapterFactory extends AssignmentsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AssignmentsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.Assignments} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssignmentsItemProvider assignmentsItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.Assignments}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssignmentsAdapter() {
		if (assignmentsItemProvider == null) {
			assignmentsItemProvider = new AssignmentsItemProvider(this);
		}

		return assignmentsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.InterfaceToPort2PortAssignmentSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceToPort2PortAssignmentSetItemProvider interfaceToPort2PortAssignmentSetItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.InterfaceToPort2PortAssignmentSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceToPort2PortAssignmentSetAdapter() {
		if (interfaceToPort2PortAssignmentSetItemProvider == null) {
			interfaceToPort2PortAssignmentSetItemProvider = new InterfaceToPort2PortAssignmentSetItemProvider(this);
		}

		return interfaceToPort2PortAssignmentSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.InterfaceToPort2PortAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceToPort2PortAssignmentItemProvider interfaceToPort2PortAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.InterfaceToPort2PortAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceToPort2PortAssignmentAdapter() {
		if (interfaceToPort2PortAssignmentItemProvider == null) {
			interfaceToPort2PortAssignmentItemProvider = new InterfaceToPort2PortAssignmentItemProvider(this);
		}

		return interfaceToPort2PortAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.DeviceToImplementationAssignmentSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeviceToImplementationAssignmentSetItemProvider deviceToImplementationAssignmentSetItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.DeviceToImplementationAssignmentSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeviceToImplementationAssignmentSetAdapter() {
		if (deviceToImplementationAssignmentSetItemProvider == null) {
			deviceToImplementationAssignmentSetItemProvider = new DeviceToImplementationAssignmentSetItemProvider(this);
		}

		return deviceToImplementationAssignmentSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.DeviceToImplementationAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeviceToImplementationAssignmentItemProvider deviceToImplementationAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.DeviceToImplementationAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeviceToImplementationAssignmentAdapter() {
		if (deviceToImplementationAssignmentItemProvider == null) {
			deviceToImplementationAssignmentItemProvider = new DeviceToImplementationAssignmentItemProvider(this);
		}

		return deviceToImplementationAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.InterfaceToHardwareAssignmentSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceToHardwareAssignmentSetItemProvider interfaceToHardwareAssignmentSetItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.InterfaceToHardwareAssignmentSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceToHardwareAssignmentSetAdapter() {
		if (interfaceToHardwareAssignmentSetItemProvider == null) {
			interfaceToHardwareAssignmentSetItemProvider = new InterfaceToHardwareAssignmentSetItemProvider(this);
		}

		return interfaceToHardwareAssignmentSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.InterfaceToHardwareAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceToHardwareAssignmentItemProvider interfaceToHardwareAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.InterfaceToHardwareAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceToHardwareAssignmentAdapter() {
		if (interfaceToHardwareAssignmentItemProvider == null) {
			interfaceToHardwareAssignmentItemProvider = new InterfaceToHardwareAssignmentItemProvider(this);
		}

		return interfaceToHardwareAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.PortToPortAssignmentSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PortToPortAssignmentSetItemProvider portToPortAssignmentSetItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.PortToPortAssignmentSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPortToPortAssignmentSetAdapter() {
		if (portToPortAssignmentSetItemProvider == null) {
			portToPortAssignmentSetItemProvider = new PortToPortAssignmentSetItemProvider(this);
		}

		return portToPortAssignmentSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.PortToPortAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PortToPortAssignmentItemProvider portToPortAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.PortToPortAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPortToPortAssignmentAdapter() {
		if (portToPortAssignmentItemProvider == null) {
			portToPortAssignmentItemProvider = new PortToPortAssignmentItemProvider(this);
		}

		return portToPortAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.ED247AssignmentSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ED247AssignmentSetItemProvider ed247AssignmentSetItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.ED247AssignmentSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createED247AssignmentSetAdapter() {
		if (ed247AssignmentSetItemProvider == null) {
			ed247AssignmentSetItemProvider = new ED247AssignmentSetItemProvider(this);
		}

		return ed247AssignmentSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.ED247Assignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ED247AssignmentItemProvider ed247AssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.ED247Assignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createED247AssignmentAdapter() {
		if (ed247AssignmentItemProvider == null) {
			ed247AssignmentItemProvider = new ED247AssignmentItemProvider(this);
		}

		return ed247AssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.UDPSocketExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UDPSocketExtensionItemProvider udpSocketExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.UDPSocketExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUDPSocketExtensionAdapter() {
		if (udpSocketExtensionItemProvider == null) {
			udpSocketExtensionItemProvider = new UDPSocketExtensionItemProvider(this);
		}

		return udpSocketExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.SWPortToHWPortAssignmentSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SWPortToHWPortAssignmentSetItemProvider swPortToHWPortAssignmentSetItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.SWPortToHWPortAssignmentSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSWPortToHWPortAssignmentSetAdapter() {
		if (swPortToHWPortAssignmentSetItemProvider == null) {
			swPortToHWPortAssignmentSetItemProvider = new SWPortToHWPortAssignmentSetItemProvider(this);
		}

		return swPortToHWPortAssignmentSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.assignments.SWPortToHWPortAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SWPortToHWPortAssignmentItemProvider swPortToHWPortAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.assignments.SWPortToHWPortAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSWPortToHWPortAssignmentAdapter() {
		if (swPortToHWPortAssignmentItemProvider == null) {
			swPortToHWPortAssignmentItemProvider = new SWPortToHWPortAssignmentItemProvider(this);
		}

		return swPortToHWPortAssignmentItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (assignmentsItemProvider != null) assignmentsItemProvider.dispose();
		if (interfaceToPort2PortAssignmentSetItemProvider != null) interfaceToPort2PortAssignmentSetItemProvider.dispose();
		if (interfaceToPort2PortAssignmentItemProvider != null) interfaceToPort2PortAssignmentItemProvider.dispose();
		if (deviceToImplementationAssignmentSetItemProvider != null) deviceToImplementationAssignmentSetItemProvider.dispose();
		if (deviceToImplementationAssignmentItemProvider != null) deviceToImplementationAssignmentItemProvider.dispose();
		if (interfaceToHardwareAssignmentSetItemProvider != null) interfaceToHardwareAssignmentSetItemProvider.dispose();
		if (interfaceToHardwareAssignmentItemProvider != null) interfaceToHardwareAssignmentItemProvider.dispose();
		if (portToPortAssignmentSetItemProvider != null) portToPortAssignmentSetItemProvider.dispose();
		if (portToPortAssignmentItemProvider != null) portToPortAssignmentItemProvider.dispose();
		if (ed247AssignmentSetItemProvider != null) ed247AssignmentSetItemProvider.dispose();
		if (ed247AssignmentItemProvider != null) ed247AssignmentItemProvider.dispose();
		if (udpSocketExtensionItemProvider != null) udpSocketExtensionItemProvider.dispose();
		if (swPortToHWPortAssignmentSetItemProvider != null) swPortToHWPortAssignmentSetItemProvider.dispose();
		if (swPortToHWPortAssignmentItemProvider != null) swPortToHWPortAssignmentItemProvider.dispose();
	}

}
