/**
 *
 * $Id$
 */
package ucof.communication.configECIC.streamTypes.validation;

import ucof.common.enums.YesNoType;

import ucof.communication.configECIC.packageStrategyTypes.A825PacketStrategy;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.streamTypes.A825Stream}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface A825StreamValidator {
	boolean validate();

	boolean validateA825PacketStrategy(A825PacketStrategy value);
	boolean validateErrors(YesNoType value);
}
