/**
 *
 * $Id$
 */
package ucof.communication.configECIC.streamTypes.validation;

import ucof.common.enums.SingleDirectionType;

import ucof.communication.configECIC.packageStrategyTypes.NADPacketStrategy;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.streamTypes.NADStream}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NADStreamValidator {
	boolean validate();

	boolean validateDirection(SingleDirectionType value);
	boolean validateSampleMaxSizeBytes(Integer value);
	boolean validateNadPacketStrategy(NADPacketStrategy value);
}
