/**
 *
 * $Id$
 */
package ucof.communication.configECIC.streamTypes.validation;

import ucof.communication.configECIC.streamTypes.DataTimestamp;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.streamTypes.SuperStreamType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperStreamTypeValidator {
	boolean validate();

	boolean validateSampleMaxNumber(Integer value);
	boolean validateIcd(String value);
	boolean validateDataTimestamp(DataTimestamp value);
}
