/**
 *
 * $Id$
 */
package targets.CanTransceiver.validation;

import targets.CanTransceiver.canTransceiverPorts;

/**
 * A sample validator interface for {@link targets.CanTransceiver.sn65hvd230}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface sn65hvd230Validator {
	boolean validate();

	boolean validatePorts(canTransceiverPorts value);

	boolean validateCanTransceiverPorts(canTransceiverPorts value);
}
