/**
 *
 * $Id$
 */
package ucof.communication.i2c.validation;

import ucof.common.enums.booleanType;

import ucof.communication.i2c.I2CAddressMode;
import ucof.communication.i2c.I2CBusMode;

/**
 * A sample validator interface for {@link ucof.communication.i2c.I2CBus}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface I2CBusValidator {
	boolean validate();

	boolean validateBusMode(I2CBusMode value);
	boolean validateAddressMode(I2CAddressMode value);
	boolean validatePullUpResistanceOhm(Integer value);
	boolean validateClockStretchingEnabled(booleanType value);
	boolean validateMultiControllerEnabled(booleanType value);
}
