/**
 *
 * $Id$
 */
package ucof.communication.i2c.validation;

import ucof.common.enums.SingleDirectionType;
import ucof.common.enums.booleanType;

import ucof.communication.i2c.I2CRegisterSpecification;

/**
 * A sample validator interface for {@link ucof.communication.i2c.I2CMessage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface I2CMessageValidator {
	boolean validate();

	boolean validateTargetAddress(String value);
	boolean validateDirection(SingleDirectionType value);
	boolean validateDataLengthBytes(Integer value);
	boolean validateRepeatedStart(booleanType value);
	boolean validateRegisterPointerByte(String value);
	boolean validateRegisterSpecification(I2CRegisterSpecification value);
}
