/**
 *
 * $Id$
 */
package ucof.communication.i2c.validation;

import ucof.common.enums.booleanType;

/**
 * A sample validator interface for {@link ucof.communication.i2c.I2CRegisterSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface I2CRegisterSpecificationValidator {
	boolean validate();

	boolean validateRegisterName(String value);
	boolean validateRegisterPointerAddress(String value);
	boolean validateRegisterWidthBits(int value);
	boolean validateDefaultValue(String value);
	boolean validateReadOnly(booleanType value);
}
