/**
 */
package ucof.devices.devicetypes.a653components.healthmanagement.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import ucof.devices.devicetypes.a653components.healthmanagement.util.HealthmanagementAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class HealthmanagementItemProviderAdapterFactory extends HealthmanagementAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public HealthmanagementItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.HealthManagement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HealthManagementItemProvider healthManagementItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.HealthManagement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHealthManagementAdapter() {
		if (healthManagementItemProvider == null) {
			healthManagementItemProvider = new HealthManagementItemProvider(this);
		}

		return healthManagementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.ModuleTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModuleTableItemProvider moduleTableItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.ModuleTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModuleTableAdapter() {
		if (moduleTableItemProvider == null) {
			moduleTableItemProvider = new ModuleTableItemProvider(this);
		}

		return moduleTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.MultiPartitionTables} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiPartitionTablesItemProvider multiPartitionTablesItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.MultiPartitionTables}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiPartitionTablesAdapter() {
		if (multiPartitionTablesItemProvider == null) {
			multiPartitionTablesItemProvider = new MultiPartitionTablesItemProvider(this);
		}

		return multiPartitionTablesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.MultiPartitionTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiPartitionTableItemProvider multiPartitionTableItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.MultiPartitionTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiPartitionTableAdapter() {
		if (multiPartitionTableItemProvider == null) {
			multiPartitionTableItemProvider = new MultiPartitionTableItemProvider(this);
		}

		return multiPartitionTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.HMTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HMTableItemProvider hmTableItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.HMTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHMTableAdapter() {
		if (hmTableItemProvider == null) {
			hmTableItemProvider = new HMTableItemProvider(this);
		}

		return hmTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.ErrorInfoSuper} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ErrorInfoSuperItemProvider errorInfoSuperItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.ErrorInfoSuper}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createErrorInfoSuperAdapter() {
		if (errorInfoSuperItemProvider == null) {
			errorInfoSuperItemProvider = new ErrorInfoSuperItemProvider(this);
		}

		return errorInfoSuperItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.ErrorInfoModule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ErrorInfoModuleItemProvider errorInfoModuleItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.ErrorInfoModule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createErrorInfoModuleAdapter() {
		if (errorInfoModuleItemProvider == null) {
			errorInfoModuleItemProvider = new ErrorInfoModuleItemProvider(this);
		}

		return errorInfoModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.ErroInfoPartition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ErroInfoPartitionItemProvider erroInfoPartitionItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.ErroInfoPartition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createErroInfoPartitionAdapter() {
		if (erroInfoPartitionItemProvider == null) {
			erroInfoPartitionItemProvider = new ErroInfoPartitionItemProvider(this);
		}

		return erroInfoPartitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.ErrorInfoMultiPartition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ErrorInfoMultiPartitionItemProvider errorInfoMultiPartitionItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.ErrorInfoMultiPartition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createErrorInfoMultiPartitionAdapter() {
		if (errorInfoMultiPartitionItemProvider == null) {
			errorInfoMultiPartitionItemProvider = new ErrorInfoMultiPartitionItemProvider(this);
		}

		return errorInfoMultiPartitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.ModuleRecoveryAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModuleRecoveryActionItemProvider moduleRecoveryActionItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.ModuleRecoveryAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModuleRecoveryActionAdapter() {
		if (moduleRecoveryActionItemProvider == null) {
			moduleRecoveryActionItemProvider = new ModuleRecoveryActionItemProvider(this);
		}

		return moduleRecoveryActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.PartitionRecoveryAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PartitionRecoveryActionItemProvider partitionRecoveryActionItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.PartitionRecoveryAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPartitionRecoveryActionAdapter() {
		if (partitionRecoveryActionItemProvider == null) {
			partitionRecoveryActionItemProvider = new PartitionRecoveryActionItemProvider(this);
		}

		return partitionRecoveryActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.a653components.healthmanagement.ProcessRevoceryAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcessRevoceryActionItemProvider processRevoceryActionItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.a653components.healthmanagement.ProcessRevoceryAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProcessRevoceryActionAdapter() {
		if (processRevoceryActionItemProvider == null) {
			processRevoceryActionItemProvider = new ProcessRevoceryActionItemProvider(this);
		}

		return processRevoceryActionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (healthManagementItemProvider != null) healthManagementItemProvider.dispose();
		if (moduleTableItemProvider != null) moduleTableItemProvider.dispose();
		if (multiPartitionTablesItemProvider != null) multiPartitionTablesItemProvider.dispose();
		if (multiPartitionTableItemProvider != null) multiPartitionTableItemProvider.dispose();
		if (hmTableItemProvider != null) hmTableItemProvider.dispose();
		if (errorInfoSuperItemProvider != null) errorInfoSuperItemProvider.dispose();
		if (errorInfoModuleItemProvider != null) errorInfoModuleItemProvider.dispose();
		if (erroInfoPartitionItemProvider != null) erroInfoPartitionItemProvider.dispose();
		if (errorInfoMultiPartitionItemProvider != null) errorInfoMultiPartitionItemProvider.dispose();
		if (moduleRecoveryActionItemProvider != null) moduleRecoveryActionItemProvider.dispose();
		if (partitionRecoveryActionItemProvider != null) partitionRecoveryActionItemProvider.dispose();
		if (processRevoceryActionItemProvider != null) processRevoceryActionItemProvider.dispose();
	}

}
