/**
 */
package ucof.devices.devicetypes.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import ucof.devices.devicetypes.util.DevicetypesAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DevicetypesItemProviderAdapterFactory extends DevicetypesAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DevicetypesItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.A653P1Module} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A653P1ModuleItemProvider a653P1ModuleItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.A653P1Module}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA653P1ModuleAdapter() {
		if (a653P1ModuleItemProvider == null) {
			a653P1ModuleItemProvider = new A653P1ModuleItemProvider(this);
		}

		return a653P1ModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.A653P4Module} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A653P4ModuleItemProvider a653P4ModuleItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.A653P4Module}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA653P4ModuleAdapter() {
		if (a653P4ModuleItemProvider == null) {
			a653P4ModuleItemProvider = new A653P4ModuleItemProvider(this);
		}

		return a653P4ModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.IOModule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IOModuleItemProvider ioModuleItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.IOModule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIOModuleAdapter() {
		if (ioModuleItemProvider == null) {
			ioModuleItemProvider = new IOModuleItemProvider(this);
		}

		return ioModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.Peripheral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PeripheralItemProvider peripheralItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.Peripheral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPeripheralAdapter() {
		if (peripheralItemProvider == null) {
			peripheralItemProvider = new PeripheralItemProvider(this);
		}

		return peripheralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.A664Switch} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A664SwitchItemProvider a664SwitchItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.A664Switch}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA664SwitchAdapter() {
		if (a664SwitchItemProvider == null) {
			a664SwitchItemProvider = new A664SwitchItemProvider(this);
		}

		return a664SwitchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.ComputingModule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComputingModuleItemProvider computingModuleItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.ComputingModule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComputingModuleAdapter() {
		if (computingModuleItemProvider == null) {
			computingModuleItemProvider = new ComputingModuleItemProvider(this);
		}

		return computingModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.devices.devicetypes.PowerRail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PowerRailItemProvider powerRailItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.devices.devicetypes.PowerRail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPowerRailAdapter() {
		if (powerRailItemProvider == null) {
			powerRailItemProvider = new PowerRailItemProvider(this);
		}

		return powerRailItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (a653P1ModuleItemProvider != null) a653P1ModuleItemProvider.dispose();
		if (a653P4ModuleItemProvider != null) a653P4ModuleItemProvider.dispose();
		if (ioModuleItemProvider != null) ioModuleItemProvider.dispose();
		if (peripheralItemProvider != null) peripheralItemProvider.dispose();
		if (a664SwitchItemProvider != null) a664SwitchItemProvider.dispose();
		if (computingModuleItemProvider != null) computingModuleItemProvider.dispose();
		if (powerRailItemProvider != null) powerRailItemProvider.dispose();
	}

}
