/**
 *
 * $Id$
 */
package ucof.communication.connectors.validation;

import org.eclipse.emf.common.util.EList;

import ucof.communication.connectors.ConnectorGroup;

/**
 * A sample validator interface for {@link ucof.communication.connectors.Connectors}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectorsValidator {
	boolean validate();

	boolean validateConnectorGroup(EList<ConnectorGroup> value);
}
