/**
 */
package ucof.communication.configECIC.streamTypes.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import ucof.communication.configECIC.streamTypes.util.StreamTypesAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class StreamTypesItemProviderAdapterFactory extends StreamTypesAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public StreamTypesItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.streamTypes.A429Stream} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A429StreamItemProvider a429StreamItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.streamTypes.A429Stream}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA429StreamAdapter() {
		if (a429StreamItemProvider == null) {
			a429StreamItemProvider = new A429StreamItemProvider(this);
		}

		return a429StreamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.streamTypes.A825Stream} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A825StreamItemProvider a825StreamItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.streamTypes.A825Stream}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA825StreamAdapter() {
		if (a825StreamItemProvider == null) {
			a825StreamItemProvider = new A825StreamItemProvider(this);
		}

		return a825StreamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.streamTypes.A664Stream} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A664StreamItemProvider a664StreamItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.streamTypes.A664Stream}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA664StreamAdapter() {
		if (a664StreamItemProvider == null) {
			a664StreamItemProvider = new A664StreamItemProvider(this);
		}

		return a664StreamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.streamTypes.ETHStream} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ETHStreamItemProvider ethStreamItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.streamTypes.ETHStream}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createETHStreamAdapter() {
		if (ethStreamItemProvider == null) {
			ethStreamItemProvider = new ETHStreamItemProvider(this);
		}

		return ethStreamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.streamTypes.DISStream} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DISStreamItemProvider disStreamItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.streamTypes.DISStream}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDISStreamAdapter() {
		if (disStreamItemProvider == null) {
			disStreamItemProvider = new DISStreamItemProvider(this);
		}

		return disStreamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.streamTypes.ANAStream} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ANAStreamItemProvider anaStreamItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.streamTypes.ANAStream}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createANAStreamAdapter() {
		if (anaStreamItemProvider == null) {
			anaStreamItemProvider = new ANAStreamItemProvider(this);
		}

		return anaStreamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.streamTypes.NADStream} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NADStreamItemProvider nadStreamItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.streamTypes.NADStream}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNADStreamAdapter() {
		if (nadStreamItemProvider == null) {
			nadStreamItemProvider = new NADStreamItemProvider(this);
		}

		return nadStreamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.streamTypes.DataTimestamp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataTimestampItemProvider dataTimestampItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.streamTypes.DataTimestamp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataTimestampAdapter() {
		if (dataTimestampItemProvider == null) {
			dataTimestampItemProvider = new DataTimestampItemProvider(this);
		}

		return dataTimestampItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (a429StreamItemProvider != null) a429StreamItemProvider.dispose();
		if (a825StreamItemProvider != null) a825StreamItemProvider.dispose();
		if (a664StreamItemProvider != null) a664StreamItemProvider.dispose();
		if (ethStreamItemProvider != null) ethStreamItemProvider.dispose();
		if (disStreamItemProvider != null) disStreamItemProvider.dispose();
		if (anaStreamItemProvider != null) anaStreamItemProvider.dispose();
		if (nadStreamItemProvider != null) nadStreamItemProvider.dispose();
		if (dataTimestampItemProvider != null) dataTimestampItemProvider.dispose();
	}

}
