#

pluginName = Ucof Editor
providerName = www.example.org

_UI_UcofEditor_menu = &Ucof Editor
_UI_EnumsEditor_menu = &Enums Editor
_UI_EtypesEditor_menu = &Etypes Editor
_UI_EdataEditor_menu = &Edata Editor
_UI_DevicesEditor_menu = &Devices Editor
_UI_DevicetypesEditor_menu = &Devicetypes Editor
_UI_A653componentsEditor_menu = &A653components Editor
_UI_A653partitionEditor_menu = &A653partition Editor
_UI_HealthmanagementEditor_menu = &Healthmanagement Editor
_UI_FunctionsEditor_menu = &Functions Editor
_UI_RoutingEditor_menu = &Routing Editor
_UI_PortsEditor_menu = &Ports Editor
_UI_CommunicationEditor_menu = &Communication Editor
_UI_Arinc429Editor_menu = &Arinc429 Editor
_UI_Arinc825Editor_menu = &Arinc825 Editor
_UI_BasedonethernetEditor_menu = &Basedonethernet Editor
_UI_Arinc664Editor_menu = &Arinc664 Editor
_UI_BasedonwiredEditor_menu = &Basedonwired Editor
_UI_ConnectorsEditor_menu = &Connectors Editor
_UI_ConfigECICEditor_menu = &ConfigECIC Editor
_UI_StreamTypesEditor_menu = &StreamTypes Editor
_UI_PackageStrategyTypesEditor_menu = &PackageStrategyTypes Editor
_UI_ComDevicesEditor_menu = &ComDevices Editor
_UI_AssignmentsEditor_menu = &Assignments Editor
_UI_DatabaseEditor_menu = &Database Editor
_UI_TargetsEditor_menu = &Targets Editor
_UI_ConfigdeskEditor_menu = &Configdesk Editor
_UI_DSpaceArinc825Editor_menu = &DSpaceArinc825 Editor
_UI_EthernetEditor_menu = &Ethernet Editor
_UI_WiredEditor_menu = &Wired Editor
_UI_Tricore299a653p4Editor_menu = &Tricore299a653p4 Editor
_UI_MatlabEditor_menu = &Matlab Editor
_UI_A653capabletargetEditor_menu = &A653capabletarget Editor
_UI_Vxworksa653Editor_menu = &Vxworksa653 Editor

_UI_CreateChild_menu_item = &New Child
_UI_CreateSibling_menu_item = N&ew Sibling

_UI_ShowPropertiesView_menu_item = Show &Properties View
_UI_RefreshViewer_menu_item = &Refresh

_UI_SelectionPage_label = Selection
_UI_ParentPage_label = Parent
_UI_ListPage_label = List
_UI_TreePage_label = Tree
_UI_TablePage_label = Table
_UI_TreeWithColumnsPage_label = Tree with Columns
_UI_ObjectColumn_label = Object
_UI_SelfColumn_label = Self

_UI_NoObjectSelected = Selected Nothing
_UI_SingleObjectSelected = Selected Object: {0}
_UI_MultiObjectSelected = Selected {0} Objects

_UI_OpenEditorError_label = Open Editor

_UI_Wizard_category = Example EMF Model Creation Wizards

_UI_CreateModelError_message = Problems encountered in file "{0}"

_UI_UcofModelWizard_label = Ucof Model
_UI_UcofModelWizard_description = Create a new Ucof model

_UI_UcofEditor_label = Ucof Model Editor

_UI_UcofEditorFilenameDefaultBase = My
_UI_UcofEditorFilenameExtensions = ucof

_UI_EnumsEditor_label = Enums Model Editor

_UI_EnumsEditorFilenameDefaultBase = My
_UI_EnumsEditorFilenameExtensions = enums

_UI_EtypesEditor_label = Etypes Model Editor

_UI_EtypesEditorFilenameDefaultBase = My
_UI_EtypesEditorFilenameExtensions = etypes

_UI_EdataEditor_label = Edata Model Editor

_UI_EdataEditorFilenameDefaultBase = My
_UI_EdataEditorFilenameExtensions = edata

_UI_DevicesEditor_label = Devices Model Editor

_UI_DevicesEditorFilenameDefaultBase = My
_UI_DevicesEditorFilenameExtensions = devices

_UI_DevicetypesEditor_label = Devicetypes Model Editor

_UI_DevicetypesEditorFilenameDefaultBase = My
_UI_DevicetypesEditorFilenameExtensions = devicetypes

_UI_A653componentsEditor_label = A653components Model Editor

_UI_A653componentsEditorFilenameDefaultBase = My
_UI_A653componentsEditorFilenameExtensions = a653components

_UI_A653partitionEditor_label = A653partition Model Editor

_UI_A653partitionEditorFilenameDefaultBase = My
_UI_A653partitionEditorFilenameExtensions = a653partition

_UI_HealthmanagementEditor_label = Healthmanagement Model Editor

_UI_HealthmanagementEditorFilenameDefaultBase = My
_UI_HealthmanagementEditorFilenameExtensions = healthmanagement

_UI_FunctionsEditor_label = Functions Model Editor

_UI_FunctionsEditorFilenameDefaultBase = My
_UI_FunctionsEditorFilenameExtensions = functions

_UI_RoutingEditor_label = Routing Model Editor

_UI_RoutingEditorFilenameDefaultBase = My
_UI_RoutingEditorFilenameExtensions = routing

_UI_PortsEditor_label = Ports Model Editor

_UI_PortsEditorFilenameDefaultBase = My
_UI_PortsEditorFilenameExtensions = ports

_UI_CommunicationEditor_label = Communication Model Editor

_UI_CommunicationEditorFilenameDefaultBase = My
_UI_CommunicationEditorFilenameExtensions = communication

_UI_Arinc429Editor_label = Arinc429 Model Editor

_UI_Arinc429EditorFilenameDefaultBase = My
_UI_Arinc429EditorFilenameExtensions = arinc429

_UI_Arinc825Editor_label = Arinc825 Model Editor

_UI_Arinc825EditorFilenameDefaultBase = My
_UI_Arinc825EditorFilenameExtensions = arinc825

_UI_BasedonethernetEditor_label = Basedonethernet Model Editor

_UI_BasedonethernetEditorFilenameDefaultBase = My
_UI_BasedonethernetEditorFilenameExtensions = basedonethernet

_UI_Arinc664Editor_label = Arinc664 Model Editor

_UI_Arinc664EditorFilenameDefaultBase = My
_UI_Arinc664EditorFilenameExtensions = arinc664

_UI_BasedonwiredEditor_label = Basedonwired Model Editor

_UI_BasedonwiredEditorFilenameDefaultBase = My
_UI_BasedonwiredEditorFilenameExtensions = basedonwired

_UI_ConnectorsEditor_label = Connectors Model Editor

_UI_ConnectorsEditorFilenameDefaultBase = My
_UI_ConnectorsEditorFilenameExtensions = connectors

_UI_ConfigECICEditor_label = ConfigECIC Model Editor

_UI_ConfigECICEditorFilenameDefaultBase = My
_UI_ConfigECICEditorFilenameExtensions = configecic

_UI_StreamTypesEditor_label = StreamTypes Model Editor

_UI_StreamTypesEditorFilenameDefaultBase = My
_UI_StreamTypesEditorFilenameExtensions = streamtypes

_UI_PackageStrategyTypesEditor_label = PackageStrategyTypes Model Editor

_UI_PackageStrategyTypesEditorFilenameDefaultBase = My
_UI_PackageStrategyTypesEditorFilenameExtensions = packagestrategytypes

_UI_ComDevicesModelWizard_label = ComDevices Model
_UI_ComDevicesModelWizard_description = Create a new ComDevices model

_UI_ComDevicesEditor_label = ComDevices Model Editor

_UI_ComDevicesEditorFilenameDefaultBase = My
_UI_ComDevicesEditorFilenameExtensions = comdevices

_UI_AssignmentsEditor_label = Assignments Model Editor

_UI_AssignmentsEditorFilenameDefaultBase = My
_UI_AssignmentsEditorFilenameExtensions = assignments

_UI_DatabaseEditor_label = Database Model Editor

_UI_DatabaseEditorFilenameDefaultBase = My
_UI_DatabaseEditorFilenameExtensions = database

_UI_TargetsEditor_label = Targets Model Editor

_UI_TargetsEditorFilenameDefaultBase = My
_UI_TargetsEditorFilenameExtensions = targets

_UI_ConfigdeskEditor_label = Configdesk Model Editor

_UI_ConfigdeskEditorFilenameDefaultBase = My
_UI_ConfigdeskEditorFilenameExtensions = configdesk

_UI_DSpaceArinc825Editor_label = DSpaceArinc825 Model Editor

_UI_DSpaceArinc825EditorFilenameDefaultBase = My
_UI_DSpaceArinc825EditorFilenameExtensions = dspacearinc825

_UI_EthernetEditor_label = Ethernet Model Editor

_UI_EthernetEditorFilenameDefaultBase = My
_UI_EthernetEditorFilenameExtensions = ethernet

_UI_WiredEditor_label = Wired Model Editor

_UI_WiredEditorFilenameDefaultBase = My
_UI_WiredEditorFilenameExtensions = wired

_UI_Tricore299a653p4Editor_label = Tricore299a653p4 Model Editor

_UI_Tricore299a653p4EditorFilenameDefaultBase = My
_UI_Tricore299a653p4EditorFilenameExtensions = tricore299a653p4

_UI_MatlabEditor_label = Matlab Model Editor

_UI_MatlabEditorFilenameDefaultBase = My
_UI_MatlabEditorFilenameExtensions = matlab

_UI_A653capabletargetEditor_label = A653capabletarget Model Editor

_UI_A653capabletargetEditorFilenameDefaultBase = My
_UI_A653capabletargetEditorFilenameExtensions = a653capabletarget

_UI_Vxworksa653Editor_label = Vxworksa653 Model Editor

_UI_Vxworksa653EditorFilenameDefaultBase = My
_UI_Vxworksa653EditorFilenameExtensions = vxworksa653

_UI_Wizard_label = New

_WARN_FilenameExtension = The file name must end in ''.{0}''
_WARN_FilenameExtensions = The file name must have one of the following extensions: {0}

_UI_ModelObject = &Model Object
_UI_XMLEncoding = &XML Encoding
_UI_XMLEncodingChoices = UTF-8 ASCII UTF-16 UTF-16BE UTF-16LE ISO-8859-1
_UI_Wizard_initial_object_description = Select a model object to create

_UI_FileConflict_label = File Conflict
_WARN_FileConflict = There are unsaved changes that conflict with changes made outside the editor.  Do you wish to discard this editor's changes?

_UI_AvipEditor_menu = &Avip Editor
_UI_AvipModelWizard_label = Avip Model
_UI_AvipModelWizard_description = Create a new Avip model
_UI_AvipEditor_label = Avip Model Editor
_UI_AvipEditorFilenameDefaultBase = My
_UI_AvipEditorFilenameExtensions = avip

_UI_RDCEditor_menu = &RDC Editor
_UI_RDCModelWizard_label = RDC Model
_UI_RDCModelWizard_description = Create a new RDC model
_UI_RDCEditor_label = RDC Model Editor
_UI_RDCEditorFilenameDefaultBase = My
_UI_RDCEditorFilenameExtensions = rdc

_UI_ADCEditor_menu = &ADC Editor
_UI_ADCModelWizard_label = ADC Model
_UI_ADCModelWizard_description = Create a new ADC model
_UI_ADCEditor_label = ADC Model Editor
_UI_ADCEditorFilenameDefaultBase = My
_UI_ADCEditorFilenameExtensions = adc

_UI_SheildEditor_menu = &Sheild Editor
_UI_MotorControllerEditor_menu = &MotorController Editor
_UI_SheildModelWizard_label = Sheild Model
_UI_SheildModelWizard_description = Create a new Sheild model
_UI_SheildEditor_label = Sheild Model Editor
_UI_SheildEditorFilenameDefaultBase = My
_UI_SheildEditorFilenameExtensions = sheild
_UI_MotorControllerModelWizard_label = MotorController Model
_UI_MotorControllerModelWizard_description = Create a new MotorController model
_UI_MotorControllerEditor_label = MotorController Model Editor
_UI_MotorControllerEditorFilenameDefaultBase = My
_UI_MotorControllerEditorFilenameExtensions = motorcontroller

_UI_I2cEditor_menu = &I2c Editor
_UI_I2cEditor_label = I2c Model Editor
_UI_I2cEditorFilenameDefaultBase = My
_UI_I2cEditorFilenameExtensions = i2c

_UI_CanTransceiverEditor_menu = &CanTransceiver Editor
_UI_HallSensorEditor_menu = &HallSensor Editor
_UI_CanTransceiverModelWizard_label = CanTransceiver Model
_UI_CanTransceiverModelWizard_description = Create a new CanTransceiver model
_UI_CanTransceiverEditor_label = CanTransceiver Model Editor
_UI_CanTransceiverEditorFilenameDefaultBase = My
_UI_CanTransceiverEditorFilenameExtensions = cantransceiver
_UI_HallSensorModelWizard_label = HallSensor Model
_UI_HallSensorModelWizard_description = Create a new HallSensor model
_UI_HallSensorEditor_label = HallSensor Model Editor
_UI_HallSensorEditorFilenameDefaultBase = My
_UI_HallSensorEditorFilenameExtensions = hallsensor

_UI_CCDPUEditor_menu = &CCDPU Editor
_UI_CCDPUModelWizard_label = CCDPU Model
_UI_CCDPUModelWizard_description = Create a new CCDPU model
_UI_CCDPUEditor_label = CCDPU Model Editor
_UI_CCDPUEditorFilenameDefaultBase = My
_UI_CCDPUEditorFilenameExtensions = ccdpu

_UI_PowerRailEditor_menu = &PowerRail Editor
_UI_PowerRailModelWizard_label = PowerRail Model
_UI_PowerRailModelWizard_description = Create a new PowerRail model
_UI_PowerRailEditor_label = PowerRail Model Editor
_UI_PowerRailEditorFilenameDefaultBase = My
_UI_PowerRailEditorFilenameExtensions = powerrail

