/**
 *
 * $Id$
 */
package ucof.validation;

import targets.Targets;

import ucof.assignments.Assignments;

import ucof.communication.Communication;

import ucof.devices.Devices;

/**
 * A sample validator interface for {@link ucof.Platform}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PlatformValidator {
	boolean validate();

	boolean validateDevices(Devices value);
	boolean validateCommunication(Communication value);
	boolean validateAssignments(Assignments value);
	boolean validateTargets(Targets value);
}
