/**
 *
 * $Id$
 */
package ucof.devices.devicetypes.a653components.healthmanagement.validation;

import ucof.devices.devicetypes.a653components.healthmanagement.ErrorLevelModule;
import ucof.devices.devicetypes.a653components.healthmanagement.ModulePartitionLevelAction;

/**
 * A sample validator interface for {@link ucof.devices.devicetypes.a653components.healthmanagement.ErrorInfoMultiPartition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ErrorInfoMultiPartitionValidator {
	boolean validate();

	boolean validateErrorLevel(ErrorLevelModule value);
	boolean validateRecoveryAction(ModulePartitionLevelAction value);
}
