/**
 *
 * $Id$
 */
package ucof.devices.devicetypes.a653components.healthmanagement.validation;

import ucof.devices.devicetypes.a653components.healthmanagement.ErrorLevelPartition;
import ucof.devices.devicetypes.a653components.healthmanagement.PartitionProcessLevelAction;

/**
 * A sample validator interface for {@link ucof.devices.devicetypes.a653components.healthmanagement.ErroInfoPartition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ErroInfoPartitionValidator {
	boolean validate();

	boolean validateErrorLevel(ErrorLevelPartition value);
	boolean validateRecoveryAction(PartitionProcessLevelAction value);
}
