/**
 *
 * $Id$
 */
package ucof.devices.devicetypes.a653components.healthmanagement.validation;

import org.eclipse.emf.common.util.EList;

import ucof.devices.devicetypes.a653components.healthmanagement.ErroInfoPartition;
import ucof.devices.devicetypes.a653components.healthmanagement.MultiPartitionTable;

/**
 * A sample validator interface for {@link ucof.devices.devicetypes.a653components.healthmanagement.HMTable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HMTableValidator {
	boolean validate();

	boolean validateTableIdentifier(String value);
	boolean validateTableName(String value);
	boolean validateMultiPartitionHMTableNameRef(MultiPartitionTable value);
	boolean validateErrorInfo(EList<ErroInfoPartition> value);
}
