/**
 *
 * $Id$
 */
package ucof.devices.validation;

import org.eclipse.emf.common.util.EList;

import ucof.devices.SuperPlatformDeviceType;

/**
 * A sample validator interface for {@link ucof.devices.Devices}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DevicesValidator {
	boolean validate();

	boolean validateDevice(EList<SuperPlatformDeviceType> value);
}
