/**
 *
 * $Id$
 */
package ucof.devices.validation;

import ucof.common.enums.ImplementationType;

import ucof.devices.functions.DeviceFunctions;

/**
 * A sample validator interface for {@link ucof.devices.SuperPlatformDeviceType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperPlatformDeviceTypeValidator {
	boolean validate();

	boolean validateDeviceFunctions(DeviceFunctions value);
	boolean validateImplementationType(ImplementationType value);
}
