/**
 *
 * $Id$
 */
package targets.PowerRail.validation;

import org.eclipse.emf.common.util.EList;

import targets.PowerRail.powerRailPort;

/**
 * A sample validator interface for {@link targets.PowerRail.powerRailPorts}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface powerRailPortsValidator {
	boolean validate();

	boolean validatePort(EList<powerRailPort> value);

	boolean validatePowerRailPort(EList<powerRailPort> value);
}
