/**
 *
 * $Id$
 */
package targets.PowerRail.validation;

import targets.PowerRail.powerRailPorts;

/**
 * A sample validator interface for {@link targets.PowerRail.powerRailTarget}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface powerRailTargetValidator {
	boolean validate();

	boolean validatePorts(powerRailPorts value);

	boolean validatePowerRailPorts(powerRailPorts value);
}
