/**
 *
 * $Id$
 */
package targets.powergrid.validation;

import org.eclipse.emf.common.util.EList;

import targets.powergrid.PowerConnection;

/**
 * A sample validator interface for {@link targets.powergrid.PowerConnectionSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PowerConnectionSetValidator {
	boolean validate();

	boolean validatePowerConnection(EList<PowerConnection> value);
}
