/**
 *
 * $Id$
 */
package targets.powergrid.validation;

import targets.powergrid.EletrcialInterfaces;

/**
 * A sample validator interface for {@link targets.powergrid.SuperPowerType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperPowerTypeValidator {
	boolean validate();

	boolean validateElectricalInterfaces(EletrcialInterfaces value);
}
