/**
 *
 * $Id$
 */
package targets.powergrid.validation;

import ucof.common.enums.booleanType;

/**
 * A sample validator interface for {@link targets.powergrid.SuperElectricalGridType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperElectricalGridTypeValidator {
	boolean validate();

	boolean validateDefinedVoltage(booleanType value);
	boolean validateNominalVoltage(double value);
}
