/**
 *
 * $Id$
 */
package targets.powergrid.validation;

import targets.powergrid.interfaceType;

/**
 * A sample validator interface for {@link targets.powergrid.SuperElectricalInterfaceType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperElectricalInterfaceTypeValidator {
	boolean validate();

	boolean validateMinVoltage(double value);
	boolean validateMaxVoltage(double value);
	boolean validateType(interfaceType value);
}
