/**
 *
 * $Id$
 */
package ucof.communication.configECIC.packageStrategyTypes.validation;

import org.eclipse.emf.common.util.EList;

import ucof.common.enums.SingleDirectionType;

import ucof.communication.configECIC.packageStrategyTypes.Gap;
import ucof.communication.configECIC.packageStrategyTypes.TriggerWords;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.packageStrategyTypes.A429PacketStrategy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface A429PacketStrategyValidator {
	boolean validate();

	boolean validateDirection(SingleDirectionType value);
	boolean validateGap(Gap value);
	boolean validateTriggerWords(EList<TriggerWords> value);
}
