/**
 *
 * $Id$
 */
package ucof.communication.configECIC.packageStrategyTypes.validation;

import ucof.communication.configECIC.packageStrategyTypes.Frames;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.packageStrategyTypes.A825PacketStrategy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface A825PacketStrategyValidator {
	boolean validate();

	boolean validateFrames(Frames value);
}
