/**
 *
 * $Id$
 */
package ucof.communication.configECIC.packageStrategyTypes.validation;

import ucof.common.enums.YesNoType;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.packageStrategyTypes.Gap}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GapValidator {
	boolean validate();

	boolean validateDurationNs(Integer value);
	boolean validateResetPeriodicTimer(YesNoType value);
}
