/**
 *
 * $Id$
 */
package ucof.communication.configECIC.packageStrategyTypes.validation;

import org.eclipse.emf.common.util.EList;

import ucof.communication.configECIC.packageStrategyTypes.TriggerWord;

/**
 * A sample validator interface for {@link ucof.communication.configECIC.packageStrategyTypes.TriggerWords}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TriggerWordsValidator {
	boolean validate();

	boolean validateTriggerWord(EList<TriggerWord> value);
}
