/**
 *
 * $Id$
 */
package ucof.devices.functions.validation;


/**
 * A sample validator interface for {@link ucof.devices.functions.FunctionLink}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FunctionLinkValidator {
	boolean validate();

	boolean validateFunctionFile(String value);
}
