/**
 *
 * $Id$
 */
package ucof.devices.functions.validation;

import ucof.devices.functions.FunctionLink;

/**
 * A sample validator interface for {@link ucof.devices.functions.SuperFunctionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperFunctionTypeValidator {
	boolean validate();

	boolean validateFunctionLink(FunctionLink value);
}
