/**
 *
 * $Id$
 */
package ucof.assignments.database.validation;

import org.eclipse.emf.common.util.EList;

import ucof.assignments.database.MessageToTargetAssignment;

/**
 * A sample validator interface for {@link ucof.assignments.database.MessageToTargetAssignmentSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MessageToTargetAssignmentSetValidator {
	boolean validate();

	boolean validateMessageToTargetAssignment(EList<MessageToTargetAssignment> value);
}
