/**
 *
 * $Id$
 */
package ucof.assignments.database.validation;

import ucof.assignments.database.payloadTargets;

/**
 * A sample validator interface for {@link ucof.assignments.database.PayloadToTargetAssignment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PayloadToTargetAssignmentValidator {
	boolean validate();

	boolean validateAssignmentTargetType(payloadTargets value);
}
