/**
 *
 * $Id$
 */
package ucof.assignments.database.validation;

import ucof.assignments.database.signalTargets;

/**
 * A sample validator interface for {@link ucof.assignments.database.SignalToTargetAssignment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SignalToTargetAssignmentValidator {
	boolean validate();

	boolean validateStartBit(int value);
	boolean validateAssignmentTargetType(signalTargets value);
	boolean validateInitialValue(float value);
}
