/**
 *
 * $Id$
 */
package targets.validation;


/**
 * A sample validator interface for {@link targets.HardwareInformation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HardwareInformationValidator {
	boolean validate();

	boolean validateHardwareTopologyName(String value);
	boolean validateNameOfHardwareSystem(String value);
	boolean validateIPAddressOfHardwareSystem(String value);
}
