/**
 *
 * $Id$
 */
package targets.validation;


/**
 * A sample validator interface for {@link targets.ResistorInfo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResistorInfoValidator {
	boolean validate();

	boolean validateResistanceOhm(int value);
	boolean validateResistorPartNumber(String value);
	boolean validateMountLocation(String value);
}
