/**
 *
 * $Id$
 */
package targets.validation;

import org.eclipse.emf.common.util.EList;

import targets.SuperTargetType;

import targets.powergrid.ElectricalPowerGridSet;
import targets.powergrid.PowerConnectionSet;

/**
 * A sample validator interface for {@link targets.Targets}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TargetsValidator {
	boolean validate();

	boolean validateTargetConfiguration(EList<SuperTargetType> value);
	boolean validatePowerConnectionSet(EList<PowerConnectionSet> value);
	boolean validateElectricalPowerGridSet(EList<ElectricalPowerGridSet> value);
}
