/**
 */
package targets.avip.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import targets.avip.util.AvipAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AvipItemProviderAdapterFactory extends AvipAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AvipItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.AvionicsVirtualDevice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AvionicsVirtualDeviceItemProvider avionicsVirtualDeviceItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.AvionicsVirtualDevice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAvionicsVirtualDeviceAdapter() {
		if (avionicsVirtualDeviceItemProvider == null) {
			avionicsVirtualDeviceItemProvider = new AvionicsVirtualDeviceItemProvider(this);
		}

		return avionicsVirtualDeviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.AVDPorts} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AVDPortsItemProvider avdPortsItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.AVDPorts}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAVDPortsAdapter() {
		if (avdPortsItemProvider == null) {
			avdPortsItemProvider = new AVDPortsItemProvider(this);
		}

		return avdPortsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.FunctionalData} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionalDataItemProvider functionalDataItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.FunctionalData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionalDataAdapter() {
		if (functionalDataItemProvider == null) {
			functionalDataItemProvider = new FunctionalDataItemProvider(this);
		}

		return functionalDataItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.AnalogueInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnalogueInputItemProvider analogueInputItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.AnalogueInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnalogueInputAdapter() {
		if (analogueInputItemProvider == null) {
			analogueInputItemProvider = new AnalogueInputItemProvider(this);
		}

		return analogueInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.AnalogueOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnalogueOutputItemProvider analogueOutputItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.AnalogueOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnalogueOutputAdapter() {
		if (analogueOutputItemProvider == null) {
			analogueOutputItemProvider = new AnalogueOutputItemProvider(this);
		}

		return analogueOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.DiscreteInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiscreteInputItemProvider discreteInputItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.DiscreteInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiscreteInputAdapter() {
		if (discreteInputItemProvider == null) {
			discreteInputItemProvider = new DiscreteInputItemProvider(this);
		}

		return discreteInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.DiscreteOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiscreteOutputItemProvider discreteOutputItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.DiscreteOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiscreteOutputAdapter() {
		if (discreteOutputItemProvider == null) {
			discreteOutputItemProvider = new DiscreteOutputItemProvider(this);
		}

		return discreteOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.XTalk} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XTalkItemProvider xTalkItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.XTalk}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXTalkAdapter() {
		if (xTalkItemProvider == null) {
			xTalkItemProvider = new XTalkItemProvider(this);
		}

		return xTalkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.A429} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A429ItemProvider a429ItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.A429}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA429Adapter() {
		if (a429ItemProvider == null) {
			a429ItemProvider = new A429ItemProvider(this);
		}

		return a429ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.A664} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A664ItemProvider a664ItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.A664}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA664Adapter() {
		if (a664ItemProvider == null) {
			a664ItemProvider = new A664ItemProvider(this);
		}

		return a664ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.CAN} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CANItemProvider canItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.CAN}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCANAdapter() {
		if (canItemProvider == null) {
			canItemProvider = new CANItemProvider(this);
		}

		return canItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.MEM} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MEMItemProvider memItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.MEM}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMEMAdapter() {
		if (memItemProvider == null) {
			memItemProvider = new MEMItemProvider(this);
		}

		return memItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.V_RTD} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected V_RTDItemProvider v_RTDItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.V_RTD}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createV_RTDAdapter() {
		if (v_RTDItemProvider == null) {
			v_RTDItemProvider = new V_RTDItemProvider(this);
		}

		return v_RTDItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.PortUserConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PortUserConfigurationItemProvider portUserConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.PortUserConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPortUserConfigurationAdapter() {
		if (portUserConfigurationItemProvider == null) {
			portUserConfigurationItemProvider = new PortUserConfigurationItemProvider(this);
		}

		return portUserConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.AVDSchedulerExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AVDSchedulerExtensionItemProvider avdSchedulerExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.AVDSchedulerExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAVDSchedulerExtensionAdapter() {
		if (avdSchedulerExtensionItemProvider == null) {
			avdSchedulerExtensionItemProvider = new AVDSchedulerExtensionItemProvider(this);
		}

		return avdSchedulerExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.SignalExtensions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SignalExtensionsItemProvider signalExtensionsItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.SignalExtensions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSignalExtensionsAdapter() {
		if (signalExtensionsItemProvider == null) {
			signalExtensionsItemProvider = new SignalExtensionsItemProvider(this);
		}

		return signalExtensionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.SignalExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SignalExtensionItemProvider signalExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.SignalExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSignalExtensionAdapter() {
		if (signalExtensionItemProvider == null) {
			signalExtensionItemProvider = new SignalExtensionItemProvider(this);
		}

		return signalExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link targets.avip.MEMPortIDExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MEMPortIDExtensionItemProvider memPortIDExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link targets.avip.MEMPortIDExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMEMPortIDExtensionAdapter() {
		if (memPortIDExtensionItemProvider == null) {
			memPortIDExtensionItemProvider = new MEMPortIDExtensionItemProvider(this);
		}

		return memPortIDExtensionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (avionicsVirtualDeviceItemProvider != null) avionicsVirtualDeviceItemProvider.dispose();
		if (avdPortsItemProvider != null) avdPortsItemProvider.dispose();
		if (functionalDataItemProvider != null) functionalDataItemProvider.dispose();
		if (analogueInputItemProvider != null) analogueInputItemProvider.dispose();
		if (analogueOutputItemProvider != null) analogueOutputItemProvider.dispose();
		if (discreteInputItemProvider != null) discreteInputItemProvider.dispose();
		if (discreteOutputItemProvider != null) discreteOutputItemProvider.dispose();
		if (xTalkItemProvider != null) xTalkItemProvider.dispose();
		if (a429ItemProvider != null) a429ItemProvider.dispose();
		if (a664ItemProvider != null) a664ItemProvider.dispose();
		if (canItemProvider != null) canItemProvider.dispose();
		if (memItemProvider != null) memItemProvider.dispose();
		if (v_RTDItemProvider != null) v_RTDItemProvider.dispose();
		if (portUserConfigurationItemProvider != null) portUserConfigurationItemProvider.dispose();
		if (avdSchedulerExtensionItemProvider != null) avdSchedulerExtensionItemProvider.dispose();
		if (signalExtensionsItemProvider != null) signalExtensionsItemProvider.dispose();
		if (signalExtensionItemProvider != null) signalExtensionItemProvider.dispose();
		if (memPortIDExtensionItemProvider != null) memPortIDExtensionItemProvider.dispose();
	}

}
