/**
 *
 * $Id$
 */
package ucof.common.etypes.validation;

import org.eclipse.emf.common.util.EList;

import ucof.common.etypes.SuperInterCommunicationPortType;

/**
 * A sample validator interface for {@link ucof.common.etypes.DevicePorts}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DevicePortsValidator {
	boolean validate();

	boolean validatePort(EList<SuperInterCommunicationPortType> value);
}
