/**
 *
 * $Id$
 */
package ucof.common.etypes.validation;

import ucof.common.enums.PortDirectionType;

/**
 * A sample validator interface for {@link ucof.common.etypes.SuperPortType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperPortTypeValidator {
	boolean validate();

	boolean validateMaxMessageSize(String value);
	boolean validatePortDirection(PortDirectionType value);
}
