/**
 *
 * $Id$
 */
package ucof.common.etypes.validation;

import java.util.Date;

/**
 * A sample validator interface for {@link ucof.common.etypes.SuperTrackingType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperTrackingTypeValidator {
	boolean validate();

	boolean validateDocumentation(String value);
	boolean validateModified(Date value);
	boolean validateModifier(String value);
	boolean validateTraceLink(String value);
	boolean validateCreated(Date value);
	boolean validateCreator(String value);
	boolean validateVersion(float value);
}
