/**
 *
 * $Id$
 */
package ucof.common.etypes.validation;

import ucof.common.etypes.DevicePorts;

/**
 * A sample validator interface for {@link ucof.common.etypes.SuperDeviceType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperDeviceTypeValidator {
	boolean validate();

	boolean validateConfigurationLink(String value);
	boolean validatePorts(DevicePorts value);
}
