/**
 *
 * $Id$
 */
package ucof.communication.basedonethernet.arinc664.validation;


/**
 * A sample validator interface for {@link ucof.communication.basedonethernet.arinc664.A664VirtualLinkOut}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface A664VirtualLinkOutValidator {
	boolean validate();

	boolean validateBAG(String value);
	boolean validateMaxFrameSize(String value);
	boolean validateOverSampling(String value);
	boolean validatePhase(String value);
}
