/**
 *
 * $Id$
 */
package ucof.communication.basedonethernet.arinc664.validation;


/**
 * A sample validator interface for {@link ucof.communication.basedonethernet.arinc664.A664Message}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface A664MessageValidator {
	boolean validate();

	boolean validateDestinationMAC(String value);
	boolean validateSourceMAC(String value);
	boolean validateEtherType(String value);
	boolean validateSourceIP(String value);
	boolean validateDestinationIP(String value);
	boolean validateDestinationPort(Integer value);
	boolean validateSourcePort(Integer value);
	boolean validateTTL(Integer value);
	boolean validateProtocol(Integer value);
	boolean validateEthernetIdentification(Integer value);
	boolean validateFlagsAndFragmentOffset(Integer value);
	boolean validateVersionAndIHL(Integer value);
	boolean validateTypeOfService(Integer value);
	boolean validateVirtualLink(Integer value);
	boolean validateVirtualLinkOffset(Integer value);
}
