/**
 *
 * $Id$
 */
package ucof.communication.basedonethernet.arinc664.validation;

import ucof.communication.basedonethernet.arinc664.A664VirtualLinkSuper;

/**
 * A sample validator interface for {@link ucof.communication.basedonethernet.arinc664.A664Bus}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface A664BusValidator {
	boolean validate();

	boolean validateVirtualLink(A664VirtualLinkSuper value);
}
