/**
 *
 * $Id$
 */
package targets.ADC.validation;

import targets.ADC.adcPorts;

/**
 * A sample validator interface for {@link targets.ADC.ads1115}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ads1115Validator {
	boolean validate();

	boolean validatePorts(adcPorts value);

	boolean validateAdcPorts(adcPorts value);
}
