/**
 *
 * $Id$
 */
package ucof.devices.devicetypes.a653components.validation;


/**
 * A sample validator interface for {@link ucof.devices.devicetypes.a653components.MemoryRegion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MemoryRegionValidator {
	boolean validate();

	boolean validateSize(String value);
	boolean validateAddress(String value);
	boolean validateAccessRights(String value);
}
