/**
 *
 * $Id$
 */
package ucof.devices.devicetypes.a653components.validation;

import org.eclipse.emf.common.util.EList;

import ucof.devices.devicetypes.a653components.PartitionTimeWindow;

/**
 * A sample validator interface for {@link ucof.devices.devicetypes.a653components.ModuleSchedule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleScheduleValidator {
	boolean validate();

	boolean validatePartitionTimeWindow(EList<PartitionTimeWindow> value);
}
