/**
 *
 * $Id$
 */
package ucof.devices.devicetypes.a653components.validation;

import ucof.common.enums.booleanType;

/**
 * A sample validator interface for {@link ucof.devices.devicetypes.a653components.PartitionTimeWindow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PartitionTimeWindowValidator {
	boolean validate();

	boolean validateDuration(String value);
	boolean validateOffset(String value);
	boolean validatePeriodicProcessingStart(booleanType value);
	boolean validatePartitionOrPortID(String value);
}
