/**
 *
 * $Id$
 */
package targets.cpn.validation;

import targets.cpn.CanOperatingMode;

/**
 * A sample validator interface for {@link targets.cpn.CanDriverConfig}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CanDriverConfigValidator {
	boolean validate();

	boolean validateInterfaceID(String value);
	boolean validateCanPeripheralInstance(String value);
	boolean validateOperatingMode(CanOperatingMode value);
	boolean validateExtendedIdEnabled(boolean value);
	boolean validateRingBufferSize(int value);
}
