/**
 *
 * $Id$
 */
package targets.cpn.validation;

import targets.cpn.CanDriverConfig;
import targets.cpn.voragoPorts;

import targets.intrepidgateway.MsgBoxExtension;

/**
 * A sample validator interface for {@link targets.cpn.va41620peb1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface va41620peb1Validator {
	boolean validate();

	boolean validatePorts(voragoPorts value);
	boolean validateMsgBoxExtension(MsgBoxExtension value);

	boolean validateCanDriverConfig(CanDriverConfig value);
}
