/**
 *
 * $Id$
 */
package targets.cpn.validation;

import org.eclipse.emf.common.util.EList;

import targets.cpn.voragoPort;

/**
 * A sample validator interface for {@link targets.cpn.voragoPorts}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface voragoPortsValidator {
	boolean validate();

	boolean validatePort(EList<voragoPort> value);
}
