<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="targets" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets"
    nsPrefix="de.ucof.model.targets">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="generateModelWizard" value="false"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Targets" eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetConfiguration" upperBound="-1"
        eType="#//SuperTargetType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="powerConnectionSet" upperBound="-1"
        eType="#//powergrid/PowerConnectionSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="electricalPowerGridSet"
        upperBound="-1" eType="#//powergrid/ElectricalPowerGridSet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperTargetType" abstract="true" eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperIOHardwareType" abstract="true"
      eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignmentSpecification"
        upperBound="-1" eType="#//SuperAssignmentSpecificationType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperClassExtensionType" abstract="true"
      eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extendedClassID" eType="ecore:EDataType ucof.ecore#//common/edata/UUIDType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperAssignmentSpecificationType" abstract="true"
      eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedAssignmentID"
        eType="ecore:EDataType ucof.ecore#//common/edata/UUIDType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeDatatypeConversion" eSuperTypes="#//SuperAssignmentSpecificationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetDataType" eType="ecore:EEnum ucof.ecore#//common/enums/TargetDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valuePrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valuePostfix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResistorInfo" eSuperTypes="#//SuperAssignmentSpecificationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resistanceOhm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resistorPartNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mountLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareInformation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardwareTopologyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameOfHardwareSystem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iPAddressOfHardwareSystem"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperHardwarePortType" abstract="true"
      eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType"/>
  <eSubpackages name="powergrid" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets/powergrid"
      nsPrefix="de.ucof.model.targets.powergrid">
    <eClassifiers xsi:type="ecore:EClass" name="SuperPowerType" abstract="true" eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="electricalInterfaces"
          eType="#//powergrid/EletrcialInterfaces" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EletrcialInterfaces" eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="electricalInterface"
          upperBound="-1" eType="#//powergrid/SuperElectricalInterfaceType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuperElectricalInterfaceType" abstract="true"
        eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minVoltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxVoltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//powergrid/interfaceType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="interfaceType">
      <eLiterals name="NotSet"/>
      <eLiterals name="sink" value="1"/>
      <eLiterals name="source" value="2"/>
      <eLiterals name="sinkSource" value="3"/>
      <eLiterals name="analogReference" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuperElectricalGridType" abstract="true"
        eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="definedVoltage" eType="ecore:EEnum ucof.ecore#//common/enums/booleanType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nominalVoltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="gridType">
      <eLiterals name="NotSet"/>
      <eLiterals name="Supply" value="1"/>
      <eLiterals name="Ground" value="2"/>
      <eLiterals name="analogReference" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerConnectionSet" eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerConnection" upperBound="-1"
          eType="#//powergrid/PowerConnection" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerConnection" eSuperTypes="ucof.ecore#//assignments/SuperAssignmentType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ElectricalPowerGridSet" eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="electricalGrid" upperBound="-1"
          eType="#//powergrid/SuperElectricalGridType" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="rdc" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets/rdc"
      nsPrefix="de.ucof.model.targets.rdc">
    <eClassifiers xsi:type="ecore:EClass" name="stm32f446re" eSuperTypes="#//powergrid/SuperPowerType #//SuperTargetType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" eType="#//rdc/stmPorts"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stmTimingConfig" eType="#//rdc/stmTimingConfig"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="msgBoxExtension" eType="#//intrepidgateway/MsgBoxExtension"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="stmTimingConfig" eSuperTypes="ucof.ecore#//common/etypes/SuperTrackingType ucof.ecore#//common/etypes/SuperIdentifierType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateDriverFrequencyHz"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateGroupDivisor1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateGroupDivisor2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateGroupDivisor3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateGroupDefaultOffset"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pwmResolutionBits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateDriverFrequencyHzSize"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateGroupDivisor1Size"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateGroupDivisor2Size"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateGroupDivisor3Size"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateGroupDefaultOffsetSize"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pwmResolutionBitsSize"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="stmPorts" eSuperTypes="ucof.ecore#//common/etypes/SuperTrackingType ucof.ecore#//common/etypes/SuperIdentifierType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1"
          eType="#//rdc/stmPort" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="stmPort" eSuperTypes="#//SuperHardwarePortType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="adc" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets/adc"
      nsPrefix="de.ucof.model.targets.adc">
    <eClassifiers xsi:type="ecore:EClass" name="ads1115" eSuperTypes="#//SuperTargetType #//powergrid/SuperPowerType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" eType="#//adc/adcPorts"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="adcPorts" eSuperTypes="ucof.ecore#//common/etypes/SuperTrackingType ucof.ecore#//common/etypes/SuperIdentifierType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1"
          eType="#//adc/adcPort" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="adcPort" eSuperTypes="#//SuperHardwarePortType #//powergrid/SuperElectricalInterfaceType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="sheild" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets/sheild"
      nsPrefix="de.ucof.model.targets.sheild">
    <eClassifiers xsi:type="ecore:EClass" name="arduinosheild" eSuperTypes="#//SuperTargetType #//SuperIOHardwareType #//powergrid/SuperPowerType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" eType="#//sheild/sheildPorts"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="sheildPorts" eSuperTypes="ucof.ecore#//common/etypes/SuperTrackingType ucof.ecore#//common/etypes/SuperIdentifierType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1"
          eType="#//sheild/sheildPort" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="sheildPort" eSuperTypes="#//SuperHardwarePortType #//powergrid/SuperElectricalInterfaceType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="motorcontroller" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets/motorcontroller"
      nsPrefix="de.ucof.model.targets.motorcontroller">
    <eClassifiers xsi:type="ecore:EClass" name="escon409510" eSuperTypes="#//SuperTargetType #//powergrid/SuperPowerType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" eType="#//motorcontroller/esconPorts"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="esconPorts" eSuperTypes="ucof.ecore#//common/etypes/SuperTrackingType ucof.ecore#//common/etypes/SuperIdentifierType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1"
          eType="#//motorcontroller/esconPort" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="esconPort" eSuperTypes="#//SuperHardwarePortType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="cantransceiver" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets/cantransceiver"
      nsPrefix="de.ucof.model.targets.cantransceiver">
    <eClassifiers xsi:type="ecore:EClass" name="sn65hvd230" eSuperTypes="#//SuperTargetType #//powergrid/SuperPowerType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" eType="#//cantransceiver/canTransceiverPorts"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="canTransceiverPorts" eSuperTypes="ucof.ecore#//common/etypes/SuperTrackingType ucof.ecore#//common/etypes/SuperIdentifierType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1"
          eType="#//cantransceiver/canTransceiverPort" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="canTransceiverPort" eSuperTypes="#//SuperHardwarePortType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="hallsensor" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets/hallsensor"
      nsPrefix="de.ucof.model.targets.hallsensor">
    <eClassifiers xsi:type="ecore:EClass" name="mts360" eSuperTypes="#//SuperTargetType #//powergrid/SuperPowerType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" eType="#//hallsensor/hallPorts"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="hallPorts" eSuperTypes="ucof.ecore#//common/etypes/SuperTrackingType ucof.ecore#//common/etypes/SuperIdentifierType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1"
          eType="#//hallsensor/hallPort" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="hallPort" eSuperTypes="#//SuperHardwarePortType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="cpn" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets/cpn"
      nsPrefix="de.ucof.model.targets.cpn">
    <eClassifiers xsi:type="ecore:EClass" name="va41620peb1" eSuperTypes="#//SuperTargetType #//powergrid/SuperPowerType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" eType="#//cpn/voragoPorts"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="msgBoxExtension" eType="#//intrepidgateway/MsgBoxExtension"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="canDriverConfig" eType="#//cpn/CanDriverConfig"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="voragoPorts" eSuperTypes="ucof.ecore#//common/etypes/SuperTrackingType ucof.ecore#//common/etypes/SuperIdentifierType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1"
          eType="#//cpn/voragoPort" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="voragoPort" eSuperTypes="#//SuperHardwarePortType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CanOperatingMode">
      <eLiterals name="NORMAL"/>
      <eLiterals name="LOOPBACK" value="1"/>
      <eLiterals name="SILENT" value="2"/>
      <eLiterals name="DIAGNOSTIC" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CanDriverConfig" eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interfaceID" eType="ecore:EDataType ucof.ecore#//common/edata/UUIDType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="canPeripheralInstance"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatingMode" eType="#//cpn/CanOperatingMode"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extendedIdEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ringBufferSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="intrepidpowergrid" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets/intrepidpowergrid"
      nsPrefix="de.ucof.model.targets.intrepidpowergrid">
    <eClassifiers xsi:type="ecore:EClass" name="intrepidElectricalGrid" eSuperTypes="#//powergrid/SuperElectricalGridType"/>
    <eClassifiers xsi:type="ecore:EClass" name="intrepidElectricalInterface" eSuperTypes="#//powergrid/SuperElectricalInterfaceType"/>
  </eSubpackages>
  <eSubpackages name="intrepidgateway" nsURI="https://gitlab.com/ucof/ucof.de/model/v001/ucof/targets/intrepidgateway"
      nsPrefix="de.ucof.model.targets.intrepidgateway">
    <eClassifiers xsi:type="ecore:EClass" name="MsgBoxExtension" eSuperTypes="#//SuperClassExtensionType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfOutgoingMailboxes"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfIncomingMailboxes"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="smallBufferSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="smallBufferCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumBufferSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumBufferCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigBufferSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigBufferCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeAddr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeAddressSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingDestinationFilter"
          upperBound="-1" eType="#//intrepidgateway/CanMailboxAddressFilter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="senderSourceFilter" upperBound="-1"
          eType="#//intrepidgateway/CanMailboxAddressFilter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingMailboxSlot"
          upperBound="-1" eType="#//intrepidgateway/CanMailboxOutSlot" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CanMailboxAddressFilter" eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CanMailboxOutSlot" eSuperTypes="ucof.ecore#//common/etypes/SuperIdentifierType ucof.ecore#//common/etypes/SuperTrackingType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="portId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceAddressSymbol"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceAddressValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationAddressSymbol"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationAddressValue"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multicast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
