/**
 *
 * $Id$
 */
package targets.CCDPU.validation;

import targets.CCDPU.voragoPorts;

/**
 * A sample validator interface for {@link targets.CCDPU.va41620peb1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface va41620peb1Validator {
	boolean validate();

	boolean validatePorts(voragoPorts value);

	boolean validateVoragoPorts(voragoPorts value);
}
