/**
 *
 * $Id$
 */
package ucof.devices.devicetypes.a653components.a653partition.validation;

import ucof.common.etypes.Memory;

import ucof.devices.devicetypes.a653components.a653partition.Criticality;
import ucof.devices.devicetypes.a653components.a653partition.Processes;

import ucof.devices.devicetypes.a653components.healthmanagement.HMTable;

import ucof.devices.ports.PartitionPorts;

/**
 * A sample validator interface for {@link ucof.devices.devicetypes.a653components.a653partition.Partition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PartitionValidator {
	boolean validate();

	boolean validateCriticality(Criticality value);
	boolean validateEntryPoint(String value);
	boolean validatePartitionPeriod(String value);
	boolean validateMemory(Memory value);
	boolean validateHmTable(HMTable value);
	boolean validatePartitionPorts(PartitionPorts value);
	boolean validateProcesses(Processes value);
	boolean validateOffset(String value);
}
