/**
 *
 * $Id$
 */
package ucof.devices.devicetypes.a653components.a653partition.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ucof.devices.devicetypes.a653components.a653partition.Processes}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessesValidator {
	boolean validate();

	boolean validateProcess(EList<ucof.devices.devicetypes.a653components.a653partition.Process> value);
}
