/**
 *
 * $Id$
 */
package ucof.devices.devicetypes.a653components.a653partition.validation;

import ucof.devices.devicetypes.a653components.a653partition.ProcessDeadlineDefinition;
import ucof.devices.devicetypes.a653components.a653partition.ProcessSynchronicity;

import ucof.devices.ports.ProcessPorts;

/**
 * A sample validator interface for {@link ucof.devices.devicetypes.a653components.a653partition.Process}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessValidator {
	boolean validate();

	boolean validateEntryPoint(String value);
	boolean validateStackSize(String value);
	boolean validateBasePriority(int value);
	boolean validatePeriod(String value);
	boolean validateTimeCapacity(int value);
	boolean validateDeadline(ProcessDeadlineDefinition value);
	boolean validateSynchronicity(ProcessSynchronicity value);
	boolean validateDuration(String value);
	boolean validateProcessPorts(ProcessPorts value);
	boolean validateOffset(String value);
}
