/**
 *
 * $Id$
 */
package ucof.assignments.validation;


/**
 * A sample validator interface for {@link ucof.assignments.SuperAssignmentType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SuperAssignmentTypeValidator {
	boolean validate();

	boolean validateSourceID(String value);
	boolean validateTargetID(String value);
}
