/**
 *
 * $Id$
 */
package ucof.assignments.validation;

import ucof.common.enums.SingleDirectionType;

/**
 * A sample validator interface for {@link ucof.assignments.UDPSocketExtension}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UDPSocketExtensionValidator {
	boolean validate();

	boolean validatePortSelection(SingleDirectionType value);
	boolean validateIpAdress(String value);
	boolean validatePort(Integer value);
}
