/**
 */
package ucof.communication.configECIC.packageStrategyTypes.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import ucof.communication.configECIC.packageStrategyTypes.util.PackageStrategyTypesAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PackageStrategyTypesItemProviderAdapterFactory extends PackageStrategyTypesAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PackageStrategyTypesItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.A429PacketStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A429PacketStrategyItemProvider a429PacketStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.A429PacketStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA429PacketStrategyAdapter() {
		if (a429PacketStrategyItemProvider == null) {
			a429PacketStrategyItemProvider = new A429PacketStrategyItemProvider(this);
		}

		return a429PacketStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.A825PacketStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A825PacketStrategyItemProvider a825PacketStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.A825PacketStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA825PacketStrategyAdapter() {
		if (a825PacketStrategyItemProvider == null) {
			a825PacketStrategyItemProvider = new A825PacketStrategyItemProvider(this);
		}

		return a825PacketStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.A664PacketStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected A664PacketStrategyItemProvider a664PacketStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.A664PacketStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createA664PacketStrategyAdapter() {
		if (a664PacketStrategyItemProvider == null) {
			a664PacketStrategyItemProvider = new A664PacketStrategyItemProvider(this);
		}

		return a664PacketStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.ETHPacketStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ETHPacketStrategyItemProvider ethPacketStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.ETHPacketStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createETHPacketStrategyAdapter() {
		if (ethPacketStrategyItemProvider == null) {
			ethPacketStrategyItemProvider = new ETHPacketStrategyItemProvider(this);
		}

		return ethPacketStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.DISPacketStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DISPacketStrategyItemProvider disPacketStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.DISPacketStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDISPacketStrategyAdapter() {
		if (disPacketStrategyItemProvider == null) {
			disPacketStrategyItemProvider = new DISPacketStrategyItemProvider(this);
		}

		return disPacketStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.ANAPacketStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ANAPacketStrategyItemProvider anaPacketStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.ANAPacketStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createANAPacketStrategyAdapter() {
		if (anaPacketStrategyItemProvider == null) {
			anaPacketStrategyItemProvider = new ANAPacketStrategyItemProvider(this);
		}

		return anaPacketStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.NADPacketStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NADPacketStrategyItemProvider nadPacketStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.NADPacketStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNADPacketStrategyAdapter() {
		if (nadPacketStrategyItemProvider == null) {
			nadPacketStrategyItemProvider = new NADPacketStrategyItemProvider(this);
		}

		return nadPacketStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.Gap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GapItemProvider gapItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.Gap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGapAdapter() {
		if (gapItemProvider == null) {
			gapItemProvider = new GapItemProvider(this);
		}

		return gapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.TriggerWords} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TriggerWordsItemProvider triggerWordsItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.TriggerWords}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTriggerWordsAdapter() {
		if (triggerWordsItemProvider == null) {
			triggerWordsItemProvider = new TriggerWordsItemProvider(this);
		}

		return triggerWordsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.TriggerWord} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TriggerWordItemProvider triggerWordItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.TriggerWord}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTriggerWordAdapter() {
		if (triggerWordItemProvider == null) {
			triggerWordItemProvider = new TriggerWordItemProvider(this);
		}

		return triggerWordItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.Frame} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrameItemProvider frameItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.Frame}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrameAdapter() {
		if (frameItemProvider == null) {
			frameItemProvider = new FrameItemProvider(this);
		}

		return frameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.LLC} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LLCItemProvider llcItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.LLC}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLLCAdapter() {
		if (llcItemProvider == null) {
			llcItemProvider = new LLCItemProvider(this);
		}

		return llcItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ucof.communication.configECIC.packageStrategyTypes.Frames} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FramesItemProvider framesItemProvider;

	/**
	 * This creates an adapter for a {@link ucof.communication.configECIC.packageStrategyTypes.Frames}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFramesAdapter() {
		if (framesItemProvider == null) {
			framesItemProvider = new FramesItemProvider(this);
		}

		return framesItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (a429PacketStrategyItemProvider != null) a429PacketStrategyItemProvider.dispose();
		if (a825PacketStrategyItemProvider != null) a825PacketStrategyItemProvider.dispose();
		if (a664PacketStrategyItemProvider != null) a664PacketStrategyItemProvider.dispose();
		if (ethPacketStrategyItemProvider != null) ethPacketStrategyItemProvider.dispose();
		if (disPacketStrategyItemProvider != null) disPacketStrategyItemProvider.dispose();
		if (anaPacketStrategyItemProvider != null) anaPacketStrategyItemProvider.dispose();
		if (nadPacketStrategyItemProvider != null) nadPacketStrategyItemProvider.dispose();
		if (gapItemProvider != null) gapItemProvider.dispose();
		if (triggerWordsItemProvider != null) triggerWordsItemProvider.dispose();
		if (triggerWordItemProvider != null) triggerWordItemProvider.dispose();
		if (frameItemProvider != null) frameItemProvider.dispose();
		if (llcItemProvider != null) llcItemProvider.dispose();
		if (framesItemProvider != null) framesItemProvider.dispose();
	}

}
